out_dir: ./results
device: cuda:0
sampling_size: 256 # if conditional choose it accordingly with dataset image size
model: unet
ckpt_file: ./models/ffhq_10m.pt
steps: 1000
seed: 0
channels: 3
batch_size: 10
conditional:
  use_conditional: True
  scale: 1.0
  dataset:
    name: CelebA
    dataset_dir: ./datasets/
    num_images: 250
  operator:
    name: inpainting
    mask_type: box # random or box
    mask_size: 128
    mask_density: 0.9
  noise:
    name: cauchy
    scale: 1.0
metric:
  name: [lpips, psnr]