out_dir: ./results
device: cuda:0
sampling_size: 256 # if conditional choose it accordingly with dataset image size
model: unet
ckpt_file: ./models/ffhq_10m.pt
steps: 1000
seed: 1
channels: 3
batch_size: 5
conditional:
  use_conditional: True
  scale: 1.0
  dataset:
    name: CelebA
    dataset_dir: ./datasets/
    num_images: 250
  operator:
    name: motion-blur
    kernel_size : 61
    intensity: 0.5
  noise:
    name: gaussian
    std: 0.10
metric:
  name: [lpips, psnr]