out_dir: ./results
device: cuda:0
sampling_size: 256 # if conditional choose it accordingly with dataset image size
model: unet
ckpt_file: ./models/ffhq_10m.pt
steps: 1000
seed: 1
channels: 3
batch_size: 10
conditional:
  use_conditional: True
  scale: 0.5
  dataset:
    name: CelebA
    dataset_dir: ./datasets/
    num_images: 250
  operator:
    name: super-resolution
    resolution_factor: 0.25
  noise:
    name: gaussian
    std: 0.05
metric:
  name: [lpips, psnr]